In [1]:
import os
os.environ['TF_GPU_ALLOCATOR'] = 'cuda_malloc_async'

In [2]:
import tensorflow as tf
from typing import Any

2026-02-02 15:38:52.259084: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-02-02 15:38:52.291388: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-02-02 15:38:52.298075: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-02-02 15:38:52.318334: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-02 15:38:53.428111: W tensorflow/compiler/tf2

In [3]:
from mobilenetv2ssd.core.config import load_config

In [4]:
main_cfg_path = "configs/train/default.yaml"
model_cfg_path = "configs/model/mobilenetv2_ssd_voc.yaml"
data_cfg_path = "configs/data/voc_224.yaml"
eval_cfg_path = "configs/eval/default.yaml"

In [5]:
config = load_config(main_cfg_path,model_cfg_path,data_cfg_path,eval_cfg_path)

In [6]:
from datasets.base import BaseDetectionDataset
from datasets.voc import VOCDataset
from datasets.transforms import Compose, build_train_transforms, build_validation_transforms

In [7]:
_OUTPUT_SIGNATURE = {
    "image": tf.TensorSpec(shape=(None, None, 3), dtype=tf.float32),
    "boxes": tf.TensorSpec(shape=(None, 4), dtype=tf.float32),
    "labels": tf.TensorSpec(shape=(None,), dtype=tf.int32),
    "image_id": tf.TensorSpec(shape=(), dtype=tf.string),
    "path": tf.TensorSpec(shape=(), dtype=tf.string),
    "orig_size": tf.TensorSpec(shape=(2,), dtype=tf.int32),
}

In [8]:
def create_training_dataset_config(config: dict[str, Any]):
    training_dataset_opts = config['data'].get('train', {})

    dataset_opts = {
        'batch_size': training_dataset_opts.get('batch_size', 5),
        'padded_shapes': {
            'boxes': training_dataset_opts.get('padded_shapes', {}).get('boxes', [None, 4]),
            'image': training_dataset_opts.get('padded_shapes', {}).get('image', [None,None, 3]),
            'labels': training_dataset_opts.get('padded_shapes', {}).get('labels', [None]),
            'image_id': training_dataset_opts.get('padded_shapes', {}).get('image_id', []),
            'path': training_dataset_opts.get('padded_shapes', {}).get('path', []),
            'orig_size': [2]
        },
        'padding_values': {
            'image': training_dataset_opts.get('padding_values', {}).get('image', 0.0),
            'boxes': training_dataset_opts.get('padding_values', {}).get('boxes', -1.0),
            'labels': training_dataset_opts.get('padding_values', {}).get('labels', -1),
        },
        'shuffle': training_dataset_opts.get('shuffle', False),
        'prefetch': training_dataset_opts.get('prefetch', False),
        'max_boxes': training_dataset_opts.get('max_boxes', 100),
        'repeat': training_dataset_opts.get('repeat', False),
    }

    return dataset_opts


In [9]:
def create_validation_dataset_config(config: dict[str, Any]):
    validation_dataset_opts = config['data'].get('val', {})

    dataset_opts = {
        'batch_size': validation_dataset_opts.get('batch_size', 5),
        'padded_shapes': {
            'boxes': validation_dataset_opts.get('padded_shapes', {}).get('boxes', [None, 4]),
            'image': validation_dataset_opts.get('padded_shapes', {}).get('image', [None,None, 3]),
            'labels': validation_dataset_opts.get('padded_shapes', {}).get('labels', [None]),
            'image_id': validation_dataset_opts.get('padded_shapes', {}).get('image_id', []),
            'path': validation_dataset_opts.get('padded_shapes', {}).get('path', []),
            'orig_size': [2]
        },
        'padding_values': {
            'image': validation_dataset_opts.get('padding_values', {}).get('image', 0.0),
            'boxes': validation_dataset_opts.get('padding_values', {}).get('boxes', -1.0),
            'labels': validation_dataset_opts.get('padding_values', {}).get('labels', 0),
        },
        'shuffle': validation_dataset_opts.get('shuffle', False),
        'prefetch': validation_dataset_opts.get('prefetch', False),
        'max_boxes': validation_dataset_opts.get('max_boxes', 100),
    }

    return dataset_opts

In [10]:
def _create_gt_mask(data):
    gt_mask = data['labels'] > 0
    data['gt_mask'] = gt_mask
    return data

In [11]:
def apply_transform(sample, transform):
        image = sample["image"]
        target = {
            "boxes": sample["boxes"],
            "labels": sample["labels"],
            "orig_size": sample["orig_size"],
        }
        image, target = transform(image, target)
        return {**sample, "image": image, "boxes": target["boxes"], "labels": target["labels"]}

In [12]:
def create_training_dataset(dataset: BaseDetectionDataset, config: dict[str,Any], transform: Compose):

    dataset_opts = create_training_dataset_config(config)

    tf_dataset = tf.data.Dataset.from_generator(dataset.generator, output_signature = _OUTPUT_SIGNATURE)

    # Shuffling the dataset
    if dataset_opts['shuffle']:
        buffer_size = min(1000, len(dataset))
        tf_dataset = tf_dataset.shuffle(buffer_size, reshuffle_each_iteration=True)

    # Turning on repeat
    if dataset_opts['repeat']:
        tf_dataset = tf_dataset.repeat()

    tf_dataset = tf_dataset.padded_batch(batch_size = dataset_opts['batch_size'], padded_shapes = dataset_opts['padded_shapes'], padding_values = {
        'boxes' : tf.constant(-1, tf.float32),
        'image' : tf.constant(0, tf.float32),
        'labels' : tf.constant(0, tf.int32),
        'image_id' : tf.constant('', tf.string),
        'path' : tf.constant('', tf.string),
        'orig_size': tf.constant(0, tf.int32)
    })

    # Mapping a valid mask function
    tf_dataset = tf_dataset.map(_create_gt_mask, num_parallel_calls = tf.data.AUTOTUNE)

    # Adding the transforms
    tf_dataset = tf_dataset.map(lambda x: apply_transform(x, transform), num_parallel_calls=tf.data.AUTOTUNE)

    # Adding prefetch
    if dataset_opts['prefetch']:
        tf_dataset = tf_dataset.prefetch(tf.data.AUTOTUNE)

    return tf_dataset
        

In [13]:
compose = build_train_transforms(config)

In [14]:
data = VOCDataset(root = config['data']['root'], split = "train", classes_file = config['data']['classes_file'], use_difficult = False)

In [15]:
dataset = create_training_dataset(dataset = data, config = config, transform = compose)

I0000 00:00:1770064735.293218    8036 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1770064735.383998    8036 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1770064735.384069    8036 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1770064735.386078    8036 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1770064735.386157    8036 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:0

In [16]:
batch = next(iter(dataset))

In [17]:
batch

{'image': <tf.Tensor: shape=(3, 300, 300, 3), dtype=float32, numpy=
 array([[[[1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          ...,
          [0.7944619 , 0.8062266 , 0.9702439 ],
          [0.793085  , 0.8048497 , 0.9734771 ],
          [0.7974553 , 0.80922   , 0.97784746]],
 
         [[1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          ...,
          [0.8008887 , 0.8126534 , 0.97681004],
          [0.8044314 , 0.8161961 , 0.9848235 ],
          [0.8008889 , 0.8126536 , 0.98128104]],
 
         [[1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          ...,
          [0.8051198 , 0.81973857, 0.971721  ],
          [0.81      , 0.82248366, 0.98039216],
          [0.8140522 , 0.8297385 , 0.97803915]],
 
         ...,


In [18]:
len(data)

5717

In [19]:
batch.keys()

dict_keys(['image', 'boxes', 'labels', 'image_id', 'path', 'orig_size', 'gt_mask'])

In [20]:
def create_validation_dataset(config: dict[str, Any], dataset: BaseDetectionDataset, transform: Compose):
    dataset_opts = create_validation_dataset_config(config)

    tf_dataset = tf.data.Dataset.from_generator(dataset.generator,output_signature = _OUTPUT_SIGNATURE)

    # Now checking for the options
    if dataset_opts['shuffle']:
        buffer_size = min(1000, len(dataset))
        tf_dataset = tf_dataset.shuffle(buffer_size, reshuffle_each_iteration=True)

    # Adding the transforms
    tf_dataset = tf_dataset.map(lambda x: apply_transform(x, transform), num_parallel_calls=tf.data.AUTOTUNE)

    # Padding the batch is crucial for the dataset
    tf_dataset = tf_dataset.padded_batch(batch_size = dataset_opts['batch_size'], padded_shapes = dataset_opts['padded_shapes'], padding_values = {
        'boxes' : tf.constant(dataset_opts['padding_values']['boxes'], tf.float32),
        'image' : tf.constant(dataset_opts['padding_values']['image'], tf.float32),
        'labels' : tf.constant(dataset_opts['padding_values']['labels'], tf.int32),
        'image_id' : tf.constant('', tf.string),
        'path' : tf.constant('', tf.string),
        'orig_size': tf.constant(0, tf.int32)
    })

    # Mapping a valid mask function
    tf_dataset = tf_dataset.map(_create_gt_mask, num_parallel_calls = tf.data.AUTOTUNE)
    


    # # Adding prefetch
    # if dataset_opts['prefetch']:
    #     tf_dataset = tf_dataset.prefetch(tf.data.AUTOTUNE)
    
    return tf_dataset

In [21]:
val_data = VOCDataset(root = config['data']['root'], split = "val", classes_file = config['data']['classes_file'], use_difficult = False)

In [22]:
val_compose = build_validation_transforms(config)

In [23]:
val_compose._transforms

In [24]:
val_dataset = create_validation_dataset(dataset = val_data, config = config, transform = val_compose)

In [25]:
batch = next(iter(val_dataset))

In [26]:
batch.keys()

dict_keys(['image', 'boxes', 'labels', 'image_id', 'path', 'orig_size', 'gt_mask'])

In [27]:
batch['boxes'] * 300

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[  20.400002,    8.8     ,  268.80002 ,  234.40001 ],
        [-300.      , -300.      , -300.      , -300.      ]],

       [[  27.6     ,    9.909911,  300.      ,  300.      ],
        [  37.2     ,  171.17117 ,   49.800003,  218.91891 ]],

       [[   0.6     ,  184.      ,  256.80002 ,  234.40001 ],
        [-300.      , -300.      , -300.      , -300.      ]]],
      dtype=float32)>

In [28]:
batch['image_id']

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'2008_000002', b'2008_000003', b'2008_000007'], dtype=object)>